plugins {
	id 'java'
	id 'jacoco'
}

repositories {
	mavenCentral()
}

jacoco {
	toolVersion = '0.8.15'
}

test {
	useJUnitPlatform()
	finalizedBy jacocoTestReport
}

jacocoTestReport {
	dependsOn test
	reports {
		html.required = true
		xml.required = false
	}
}

dependencies {
	testImplementation 'org.assertj:assertj-core:3.27.7'
	testImplementation 'org.junit.jupiter:junit-jupiter:6.1.3'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}